languageCode = "en-us"
title = "Phillip Thomas"
author = "Phillip Thomas"
baseurl = "http://backlogweb.com/"
theme = "hugo-uno"

[Params]
  name = "Phillip Thomas"
  about = "Software Engineer"
  github = "pthomas931"
  stackoverflow = "5790134"
  email = "pthomas931@gmail.com"
  description = "Full stack developer"
  favicon = "/images/favicon.ico"
  cover = "/images/background-cover.jpg"